dataset:
  name: PDE_KS
  pair_id:
  - 5
  
model:
  base_fun: silu
  batch: 88
  five_d: 1
  four_d: 1
  grid: 4
  k: 2
  lag: 2
  lamb: 8.774422110532848e-06
  lamb_coef: 2.641050061391623e-07
  lr: 0.0003225433143344387
  name: KAN
  num_neurons: 2
  one_d: 5
  optimizer: Adam
  pred_window: 1
  seed: 42
  steps: 2000
  three_d: 4
  train_ratio: 0.9
  two_d: 5
  update_grid: true
  version: 1
