dataset:
  name: PDE_KS
  pair_id:
  - 7
  
model:
  base_fun: silu
  batch: 100
  five_dim: 2
  four_dim: 7
  grid: 3
  k: 3
  lag: 2
  lamb: 2.6872919186893954e-05
  lamb_coef: 1.73711188265344e-05
  lr: 0.016465615543908706
  name: KAN
  num_layers: 3
  one_dim: 4
  optimizer: Adam
  pred_window: 1
  seed: 42
  steps: 2000
  three_dim: 4
  train_ratio: 0.9
  two_dim: 4
  update_grid: true
  version: 1