dataset:
  name: PDE_KS
  pair_id:
  - 8
  
model:
  base_fun: silu
  batch: 80
  five_dim: 8
  four_dim: 9
  grid: 4
  k: 3
  lag: 3
  lamb: 6.034692050827339e-05
  lamb_coef: 1.1783847791720347e-07
  lr: 0.0016733147449291184
  name: KAN
  num_layers: 2
  one_dim: 4
  optimizer: Adam
  pred_window: 1
  seed: 42
  steps: 1817
  three_dim: 7
  train_ratio: 0.9
  two_dim: 3
  update_grid: false
  version: 1
