dataset:
  name: ODE_Lorenz
  pair_id:
  - 6

model:
  base_fun: silu
  batch: -1
  five_d: 1
  four_d: 3
  grid: 2
  k: 1
  lag: 2
  lamb: 3.104824954182164e-05
  lamb_coef: 2.537269147530943e-06
  lr: 0.008184952664004609
  name: KAN
  num_neurons: 4
  one_d: 3
  optimizer: Adam
  pred_window: 1
  seed: 42
  steps: 3690
  three_d: 2
  train_ratio: 0.9
  two_d: 2
  update_grid: false
  version: 1