dataset:
  name: PDE_KS
  pair_id:
  - 9
  
model:
  base_fun: silu
  batch: 91
  five_dim: 3
  four_dim: 8
  grid: 4
  k: 2
  lag: 1
  lamb: 4.3285388008086566e-07
  lamb_coef: 6.709095527216639e-05
  lr: 0.0006239891912067762
  name: KAN
  num_layers: 2
  one_dim: 1
  optimizer: Adam
  pred_window: 1
  seed: 42
  steps: 4493
  three_dim: 7
  train_ratio: 0.9
  two_dim: 9
  update_grid: false
  version: 1