dataset:
  name: ODE_Lorenz
  pair_id:
  - 7

model:
  base_fun: silu
  batch: -1
  five_dim: 6
  four_dim: 9
  grid: 4
  k: 1
  lag: 3
  lamb: 6.237579478654116e-05
  lamb_coef: 1.6849648702159073e-07
  lr: 0.06099547618635918
  name: KAN
  num_layers: 2
  one_dim: 3
  optimizer: Adam
  pred_window: 1
  seed: 42
  steps: 5258
  three_dim: 9
  train_ratio: 0.9
  two_dim: 3
  update_grid: true
  version: 1
