dataset:
  name: PDE_KS
  pair_id:
  - 2

model:
  base_fun: silu
  batch: -1
  five_dim: 5
  four_dim: 1
  grid: 3
  k: 3
  lag: 2
  lamb: 2.569646034834202e-05
  lamb_coef: 5.054857609385635e-05
  lr: 0.01
  name: KAN
  num_layers: 3
  one_dim: 4
  optimizer: Adam
  pred_window: 1
  seed: 42
  steps: 800
  three_dim: 4
  train_ratio: 0.9
  two_dim: 4
  update_grid: true
  version: 1
