dataset:
  name: PDE_KS
  pair_id:
  - 2

model:
  base_fun: silu
  batch: -1
  five_d: 5
  four_d: 1
  grid: 3
  k: 3
  lag: 2
  lamb: 2.569646034834202e-05
  lamb_coef: 5.054857609385635e-05
  lr: 0.01
  name: KAN
  num_neurons: 3
  one_d: 4
  optimizer: Adam
  pred_window: 1
  seed: 42
  steps: 800
  three_d: 4
  train_ratio: 0.9
  two_d: 4
  update_grid: true
  version: 1
