dataset:
  name: ODE_Lorenz
  pair_id:
  - 8
  
model:
  base_fun: silu
  batch: -1
  five_dim: 6
  four_dim: 3
  grid: 4
  k: 1
  lag: 2
  lamb: 3.07856434805649e-05
  lamb_coef: 2.3476508516227888e-07
  lr: 4.671474596304974e-05
  name: KAN
  num_layers: 4
  one_dim: 3
  optimizer: Adam
  pred_window: 1
  seed: 42
  steps: 7455
  three_dim: 2
  train_ratio: 0.9
  two_dim: 2
  update_grid: true
  version: 1