dataset:
  name: ODE_Lorenz
  pair_id:
  - 1
  
model:
  base_fun: silu
  batch: -1
  five_dim: 1
  four_dim: 3
  grid: 4
  k: 2
  lag: 5
  lamb: 3.322037604209221e-06
  lamb_coef: 4.400901750329171e-06
  lr: 0.0002631151592053886
  name: KAN
  num_layers: 4
  one_dim: 3
  optimizer: Adam
  pred_window: 1
  seed: 42
  steps: 2693
  three_dim: 2
  train_ratio: 0.9
  two_dim: 2
  update_grid: true
  version: 1