dataset:
  name: ODE_Lorenz
  pair_id:
  - 4

model:
  base_fun: silu
  batch: -1
  five_d: 3
  four_d: 1
  grid: 3
  k: 2
  lag: 23
  lamb: 5.062257674173711e-05
  lamb_coef: 2.3106625011063424e-06
  lr: 0.008963616039591503
  name: KAN
  num_neurons: 1
  one_d: 5
  optimizer: Adam
  pred_window: 1
  seed: 42
  steps: 1875
  three_d: 2
  train_ratio: 0.9
  two_d: 4
  update_grid: true
  version: 1