dataset: 
  name: KS_Official
  pair_id: 
  - 6

model:
  name: KAN
  version: 1 
  train_split: 0.8
  seed: 42
  train_ratio: 0.9
  pred_window: 1
  optimizer: 'Adam'
  base_fun: 'silu'
  update_grid: True



hyperparameters:
  steps:
    type: randint
    lower_bound: 50
    upper_bound: 10000
  
  lag:
    type: randint
    lower_bound: 1
    upper_bound: 2

  batch:
    type: choice
    choices: [-1, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
            61, 62, 63, 64, 65, 66, 67, 68, 69, 70,
            71, 72, 73, 74, 75, 76, 77, 78, 79, 80,
            81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
            91, 92, 93, 94, 95, 96, 97, 98, 99, 100]
  
  lr:
    type: loguniform
    lower_bound: 1.0e-05
    upper_bound: 1.0e-01

  num_layers: 
    type: randint
    lower_bound: 1
    upper_bound: 5
  
  one_dim:
    type: randint
    lower_bound: 1
    upper_bound: 10

  two_dim:
    type: randint
    lower_bound: 1
    upper_bound: 10

  three_dim:
    type: randint
    lower_bound: 1
    upper_bound: 10
  
  four_dim:
    type: randint
    lower_bound: 1
    upper_bound: 10
  
  five_dim:
    type: randint
    lower_bound: 1
    upper_bound: 10
  
  grid:
    type: randint
    lower_bound: 1
    upper_bound: 100
  
  k: 
    type: randint
    lower_bound: 1
    upper_bound: 3
  
  lamb: 
    type: loguniform
    lower_bound: 1.0e-07
    upper_bound: 1.0e-03
  
  lamb_coef: 
    type: loguniform
    lower_bound: 1.0e-07
    upper_bound: 1.0e-03

